name: jupyter-flex
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - notebook
  - jupyterlab
  - nbconvert
  - voila
  - ipywidgets
  - versioneer
  - twine
  # Docs
  - mkdocs
  - mkdocs-material
  - libsass
  - pygments
  - pymdown-extensions
  # Used by examples
  - pandas
  - scipy
  - matplotlib
  - plotly
  - bokeh
  - bqplot
  - pandas-datareader
  - scikit-learn
  - statsmodels
  - colorlover
  - pip:
    - jupyter-flex
    - mkdocs-jupyter
    - jupyter_bokeh
